[package]
name = "tour"
version = "0.1.0"
authors = ["Olivier ROLAND <newca12@users.noreply.github.com>"]
edition = "2024"

[dependencies]
antlr4rust = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }